#!/bin/bash
echo "=== BoltBite Server Diagnostics ==="
echo ""
echo "1. Service Status:"
echo "   Nginx: $(sudo systemctl is-active nginx)"
echo "   PHP-FPM: $(sudo systemctl is-active php8.1-fpm)"
echo ""
echo "2. Port Listening:"
sudo ss -tlnp | grep -E ":(80|443)" | awk '{print "   " $4}'
echo ""
echo "3. Domain Resolution:"
echo "   b01812585-uws24.duckdns.org -> $(dig +short b01812585-uws24.duckdns.org)"
echo ""
echo "4. Internal Server Test:"
curl -I -k https://b01812585-uws24.duckdns.org 2>&1 | head -3 | grep -E "(HTTP|server)" || echo "   Unable to connect"
echo ""
echo "5. Important Notes:"
echo "   If external access fails, check AWS EC2 Security Group settings:"
echo "   - Inbound rules must allow HTTP (80) and HTTPS (443)"
echo "   - Source should be set to 0.0.0.0/0 (allow all IPs)"
echo ""
